# launch.json to DEBUG:

# {
#   "name": "Eval Model",
#   "type": "debugpy",
#   "request": "launch",
#   "program": "${file}",
#   "console": "integratedTerminal",
#   "args": [
#       "--settings_path",
#       "scripts/settings.yaml",
#   ],
#   "justMyCode": false,
#   "purpose": [
#       "debug-in-terminal"
#   ]
# }

# RUN:

# python scripts/eval_model.py --settings_path scripts/settings.yaml

lm_eval_settings:
  autorization_token: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzTjJsWV8wUkhhdll1NEVmS21MZWJ4TmpzODhzNFdHUzZvQmV1UFRjVzhFIn0.eyJleHAiOjE3MjY2OTcwNDksImlhdCI6MTcyNjY3OTA0OSwianRpIjoiNzRjNmZkZDAtOGYyOS00ZmFjLTllYTAtN2QzZTY1YTNjN2YzIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLmRldi5uZW9zcGFjZS5haS9yZWFsbXMvbmVvc3BhY2UiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMGZjYzVhYTktZWUzYS00ZWI4LTk3ZGQtZDJmYzYzYWU4M2M4IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiMTVkMjBjMGMtMTJmYy00ZDg0LTg4YjQtY2ZkNzVmZDA3Mzc1Iiwic2lkIjoiNWFhM2QzMDgtNDg5Yy00OTFiLTk4YjgtMThhMWI0ZmJmMDY4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjgwMDAvKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1uZW9zcGFjZSIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IklzYWFjIGNhbWFyZ29zIiwic3BhY2VzIjoiW1wiYTg3YzA5YjgtMmIyOC00NmY5LTlhNDAtMGViYTkzZjA4MzBiXCJdIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiaXNhYWNAbmVvc3BhY2UuYWkiLCJnaXZlbl9uYW1lIjoiSXNhYWMiLCJmYW1pbHlfbmFtZSI6ImNhbWFyZ29zIiwiZW1haWwiOiJpc2FhY0BuZW9zcGFjZS5haSJ9.RlSmq-pccEZPT2eAo7AaSXIqxlGCsW8eBHESDWMuMWZynqCJA1IRcsWikUDuhXS6wCxuKi9ERcdlJFS50M47OjtIl5sxoGXMGML172LdTllLUve8Z69FqxxCytHq9ojVeI1FZke9dEDlITy5QX4GdUCRvTTnSSqvDF_m3lFHITiQnoDsAFQfa6-StU86rhTQkMG4pKMyfeO7ArO4N_qBspAhrQb3ZZ_uAFF4svbo3gQoOoyogvOfqPkd85MpW145vcI4P2C5nyrLLgQtjImZ2YAdqNbQxb7M9R1ZGih9BtVRaY-WLQx2uOKl2jqUwsqT8LEHy6ZsPZj4lH4MMqjhqw"
  url: "https://portal.api.dev.neospace.ai/mercury/v2/spaces/a87c09b8-2b28-46f9-9a40-0eba93f0830b/models"
  model_checkpoint: ["/cortex-cycles/neolang-pre-8b-with-sft-dataset_v3_corrected_mechanics/executions/e52e09e6-e394-4418-b731-885a7cdc3c47/jobs/neolang-pre-8b-with-sft-dataset_v3_corrected_mechanics/epoch_000011_step_001364", "/cortex-cycles/neolang-pre-8b-large-data-eval-test/executions/3364c614-ed11-4ed6-b993-2058a238c931/jobs/neolang-pre-8b-large-data-eval-test/epoch_000002_step_000010", "/cortex/outputs/finetuning/tests-joao/train-llama8B-from-cosine_annealing/checkpoints/epoch_000006"]
  model: "local-completions"
  model_name: 'eval-test'
  tasks: "minhas_vantagens_multiple_choice_new" # "minhas_vantagens" # "minhas_vantagens_multiple_choice_new"
  output_path: "results/" 
  num_concurrent: 20  
  max_retries: 3
  tokenized_requests: false
  delete_result_after_preprocess: true
